---
helmDefaults:
  wait: true
  timeout: 900
repositories:
  - name: ollama
    url: https://otwld.github.io/ollama-helm/
  - name: open-webui
    url: https://helm.openwebui.com/
releases:
  - name: ollama
    chart: ollama/ollama
    namespace: ai
    # TODO: reference external files for all this jazz
    values:
      - image:
          tag: latest
        persistentVolume:
          enabled: true
      # - name: runtimeClassName
      #   value: nvidia
  - name: open-webui
    chart: open-webui/open-webui
    namespace: ai
    hooks:
      - events: ["prepare", "presync"]
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "kube-vip-cloud-controller.yaml"
    needs:
      - ai/ollama
    values:
      - image:
          tag: latest
        ingress:
          className: nginx
          enabled: true
          host: ai.dev.home.arpa
          tls: false
          annotations:
            "kube-vip.io/loadbalancerIPs": 10.200.200.253
        service:
          type: LoadBalancer
          loadBalancerClass: "kube-vip.io/kube-vip-class"
    # Y COME NO WORKY?
    # jsonPatches:
    #   - target:
    #       version: v1
    #       kind: Service
    #       name: open-webui
    #     patch:
    #       - op: replace
    #         path: /spec/loadBalancerIP
    #         value: "10.200.200.253"
    # strategicMergePatches:
    #   - apiVersion: v1
    #     kind: Service
    #     metadata:
    #       name: open-webui
    #     spec:
    #       loadBalancerIP: 10.200.200.253
