helmDefaults:
  wait: true
  timeout: 900 # we might run on slow af systems...
repositories:
  - name: rancher
    url: https://releases.rancher.com/server-charts/latest
  - name: neuvector
    url: https://neuvector.github.io/neuvector-helm
  - name: longhorn
    url:  https://charts.longhorn.io
releases:
  - name: rancher
    namespace: cattle-system
#    version: "2.8.4"
    chart: rancher/rancher
    values:
      - hostname: vip.dev.home.arpa
        bootstrapPassword: changeme
        ingress:
          tls:
            source: secret
        replicas: 1
  # Install longhorn/neuvector after rancher is setup
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    values:
      - defaultClassReplicaCount: 1
        csi:
          attacherReplicaCount: 1
          provisionerReplicaCount: 1
          resizerReplicaCount: 1
          snapshotterReplicaCount: 1
  - name: neuvector
    namespace: cattle-neuvector-system
    chart: neuvector/core
    values:
      - global:
          cattle:
            url: https://vip.dev.home.arpa
        rbac: true
        controller:
          ranchersso:
            enabled: true
          replicas: 1
          configmap:
            enabled: true
          data:
            sysinitcg.yaml:
              New_Service_Profile_Baseline: basic
              Scan_Config:
                Auto_Scan: true
        cve:
          scanner:
            replicas: 1
        manager:
          replicas: 1
        # internal:
        #   certmanager:
        #     enabled: true
        #     secretname: neuvector-internal
        #   autoGenerateCert: true
        #   autoRotateCert: false
