---
# Note: split apart as without helm diff fails with Issuer crd's that
# don't exist trying to figure out what rancher actions will be
# performed.
repositories:
  - name: jetstack
    url: https://charts.jetstack.io
releases:
  - name: cert-manager
    namespace: cert-manager
    version: "v1.15.0"
    chart: jetstack/cert-manager
    wait: true
    set:
      - name: crds.enabled
        value: true
